// <auto-generated />
namespace MarketPlace.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class cartadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cartadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201912312101544_cart-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
