name: MarketPlace Build Work Flow

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild
      working-directory: iMarketPlace
      run: echo ls
