name: MarketPlace Build Work Flow
on: push
jobs:
  build:
    name: MSBuild
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Restore Packages
      uses: nuget restore iMarketPlace.sln
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      run: msbuild iMarketPlace.sln
      shell: cmd
